#!/usr/bin/env bash

SCRIPT_PATH="$(dirname "$(readlink "$0" || echo "$0")")"
cd "$SCRIPT_PATH" || {
    echo "Failed to change directory" >&2
    exit 1
}

while true; do
    CHOICE=$(gum choose $(ls -1 *.sh 2>/dev/null | sed 's/\.sh$//' | sort) quit)

    if [[ -z "$CHOICE" || "$CHOICE" == "quit" ]]; then
        echo "Goodbye." >&2
        exit 0
    fi

    "./$CHOICE.sh"
done
